spring.application.name=bug-tracking-application

# DataSource (Neon Postgres)
spring.datasource.url=postgresql://neondb_owner:npg_hwzV84WEaHgS@ep-solitary-bread-a1acox3a-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hwzV84WEaHgS

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Optional: Connection pool tuning
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2